name: droneMapping
channels:
  - conda-forge
  - defaults
dependencies:
  - python
  - pandas
  - geopandas
  - shapely.geometry
  - pyproj
  - matplotlib.pyplot
  - cartopy>=0.21
  - notebook
  - rasterio
  - pyepsg
  - folium
  - exifread
